version: 2.1
executors:
  cibi:
    docker:
    - image: quay.io/tenjin/cibi:latest
workflows:
  version: 2
  deploy:
    jobs:
      - kafka-deploy-staging:
          filters:
            branches: { only: tenjin }
            tags: { only: /.*/ }
      - zookeeper-deploy-staging:
          filters:
            branches: { only: tenjin }
            tags: { only: /.*/ }
      - review-gate:
          type: approval
          requires: [kafka-deploy-staging, zookeeper-deploy-staging]
          filters:
            branches: { only: tenjin }
            tags: { only: /.*/ }
      - kafka-deploy-production:
          requires: [review-gate]
          filters:
            branches: { only: tenjin }
            tags: { only: /.*/ }
      - zookeeper-deploy-production:
          requires: [review-gate]
          filters:
            branches: { only: tenjin }
            tags: { only: /.*/ }
jobs:
  kafka-deploy-staging:
    executor: cibi
    environment:
      NAME: kafka
      DOCKERFILE: ./debian/kafka/Dockerfile
      ENVIRONMENT: staging
      REGISTRY_URL: 089955869835.dkr.ecr.us-east-1.amazonaws.com/tenjin
      CI_ROLE_ARN: arn:aws:iam::089955869835:role/k8s-continuous-integration
      DEPLOY_ROLE_ARN: unused
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Push to Container Registry
        command: |
          /script/credentials
          /script/login
          /script/docker
          /script/push
  kafka-deploy-production:
    executor: cibi
    environment:
      NAME: kafka
      DOCKERFILE: ./debian/kafka/Dockerfile
      ENVIRONMENT: production
      REGISTRY_URL: 038620613384.dkr.ecr.us-east-1.amazonaws.com/tenjin
      CI_ROLE_ARN: arn:aws:iam::038620613384:role/k8s-continuous-integration
      DEPLOY_ROLE_ARN: unused
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Push to Container Registry
        command: |
          /script/credentials
          /script/login
          /script/docker
          /script/push
  zookeeper-deploy-staging:
    executor: cibi
    environment:
      NAME: kafka
      DOCKERFILE: ./debian/kafka/Dockerfile
      ENVIRONMENT: staging
      REGISTRY_URL: 089955869835.dkr.ecr.us-east-1.amazonaws.com/tenjin
      CI_ROLE_ARN: arn:aws:iam::089955869835:role/k8s-continuous-integration
      DEPLOY_ROLE_ARN: unused
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Push to Container Registry
        command: |
          /script/credentials
          /script/login
          /script/docker
          /script/push
  zookeeper-deploy-production:
    executor: cibi
    environment:
      NAME: kafka
      DOCKERFILE: ./debian/kafka/Dockerfile
      ENVIRONMENT: production
      REGISTRY_URL: 038620613384.dkr.ecr.us-east-1.amazonaws.com/tenjin
      CI_ROLE_ARN: arn:aws:iam::038620613384:role/k8s-continuous-integration
      DEPLOY_ROLE_ARN: unused
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Push to Container Registry
        command: |
          /script/credentials
          /script/login
          /script/docker
          /script/push
